version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Optionally set the version of Python and other tools you require
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt